In [15]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

In [6]:
with tf.variable_scope('my_scope'):
    weights1 = tf.Variable(tf.random_normal([10, 10]), name='weights1')
    weights2 = tf.Variable(tf.random_normal([5, 5]), name='weights2')

In [7]:
weights1

<tf.Variable 'my_scope/weights1:0' shape=(10, 10) dtype=float32_ref>

In [10]:
a = tf.placeholder(tf.float32)

b = a * 2

dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }
with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2023-09-19 01:15:22.713151: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-09-19 01:15:22.713984: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-09-19 01:15:22.749660: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-09-19 01:15:22.751178: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [16]:
init = tf.constant(np.random.rand(1, 2))
tf.get_variable('var_name', initializer=init)

<tf.Variable 'var_name:0' shape=(1, 2) dtype=float64_ref>

In [18]:
print(init)

Tensor("Const:0", shape=(1, 2), dtype=float64)


In [34]:
l = tf.constant([1, 2, 3, 4, 5, 6])

with tf.Session() as sess:
    print(l.eval())

[1 2 3 4 5 6]


2023-09-19 01:56:21.369786: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-09-19 01:56:21.369818: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-09-19 01:56:21.371500: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


In [26]:
l = tf.constant([1, 2, 3, 4, 5, 6])
tf.print(l)

<tf.Operation 'PrintV2' type=PrintV2>

In [22]:
# Create a session
session = tf.Session()

# Print the value of the tensor object
print(session.run(l))

[1 2 3 4 5 6]


2023-09-19 01:43:21.604070: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-09-19 01:43:21.604937: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-09-19 01:43:21.637623: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


In [21]:
tf.constant([1, 2, 3, 4, 5, 6])

<tf.Tensor 'Const_2:0' shape=(6,) dtype=int32>

In [36]:
import tensorflow as tf

a = tf.add(1, 2, name="Add_these_numbers")
b = tf.multiply(a, 3)
c = tf.add(4, 5, name="And_These_ones")
d = tf.multiply(c, 6, name="Multiply_these_numbers")
e = tf.multiply(4, 5, name="B_add")
f = tf.divide(c, 6, name="B_mul")
g = tf.add(b, d)
h = tf.multiply(g, f)

with tf.Session() as sess:
    writer = tf.summary.FileWriter("output", sess.graph)
    print(sess.run(h))
    writer.close()

TypeError: Input 'y' of 'Mul' Op has type float64 that does not match type int32 of argument 'x'.